package org.overstock.producers;

import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.Schema;

import java.util.Date;

public class JsonStringToBytesProducer {

    public static String topic = "auto_produce_bytes";

    public static void main(String[] args) throws Exception
    {
        try (PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();
             Producer producer = client.newProducer(Schema.AUTO_PRODUCE_BYTES()).topic(topic).create();)
        {
            long startTime = new Date().getTime();
            int i = 0;
            while (i < 100000)
            {
                String message = "{\"field1\": 2, \"field2\": \"boo\", \"field3\": 100, \"field4\": \"Lorem ipsum dolor sit amet, tincidunt ultricies eu, ut dictumst hendrerit varius mauris, est elit deserunt nam egestas, vel suspendisse risus, wisi facilisis vitae consectetuer condimentum. Leo sociis maecenas nibh aliquet, hymenaeos purus orci feugiat, suspendisse vestibulum leo massa, elit in mollis sit, nec dui vitae. A auctor sit turpis mi enim placerat, vitae aliquet risus vulputate odio. Quam ac orci ut ultrices. Pretium aliquam massa esse felis nulla, condimentum tellus in nulla facilisi interdum, at nunc ut vel lobortis, ultricies dolor praesent aliquam senectus pulvinar aliquam. Et tellus, urna dis dapibus sit dolor pulvinar, velit rutrum porro sociosqu diam taciti, inceptos ac urna curabitur erat, dui etiam augue in. Viverra aut nisl eget sit eu sed, in rutrum, euismod neque dolor quis sit, sed pharetra. Consectetuer mattis, tincidunt integer ante aenean sed aliquam orci. Sit id, ornare turpis, pharetra vestibulum, integer non volutpat velit. Corporis pellentesque donec aliquam pede aliquam interdum, wisi neque etiam ut, morbi risus vel amet eget, nec suspendisse vestibulum netus felis purus, lectus sapien. Libero ut sollicitudin ac nibh. Feugiat convallis massa urna, sodales cras urna curabitur commodo mauris, donec elit vivamus.\n" +
                        "\n" +
                        "Praesent nonummy et ac wisi, a vitae habitant vitae eros, cum conubia dictumst tristique justo. Et non magna urna magna vestibulum, a porta sem leo quia posuere nulla. Nisl elit duis varius, lectus dapibus nunc gravida, porttitor neque et elit. Sit dolor laoreet luctus, consequat viverra aliquam, adipiscing nam eros auctor. Mi morbi nec fusce, urna etiam rhoncus ut. Sit enim quis donec, ante taciti risus velit lacus nonummy sed, aut id.\n" +
                        "\n" +
                        "Scelerisque eget lacus fusce quis id velit, consectetuer id, id quam fringilla duis. Etiam dolor mattis, magna fusce, eleifend lectus parturient eu proin aliquam commodo. Eu eget. Non at nec cursus condimentum, ac orci libero penatibus, quis sollicitudin, mauris est tincidunt, varius at. Litora sed mauris morbi fusce, maecenas volutpat, fusce sit. Urna purus congue dolor. Ante nulla habitasse, aut luctus aliquam nec tellus quam commodo, phasellus gravida sed.\n" +
                        "\n" +
                        "Sit ante et. Tempor arcu faucibus ultricies tincidunt, quam vitae, diam suspendisse vel aliquam nisl metus, lorem class augue vestibulum ipsum. Vehicula dictum at, dignissim quis ridiculus duis ipsum sem varius, sed adipiscing massa urna condimentum sit non. Et in blandit viverra semper et, nisl curabitur, elit eu ac, dolor ut suspendisse gravida. In arcu, suscipit vivamus, ligula non natoque litora neque ut donec, tellus posuere donec metus dolor urna ac. Molestiae feugiat tellus sodales. Id etiam iaculis vestibulum orci et lacus, suspendisse interdum maecenas, a rhoncus leo orci per felis, laoreet luctus.\n" +
                        "\n" +
                        "Cras eros accumsan eum fames consectetuer taciti, rutrum a tincidunt ac quis leo, sit eget fringilla, vulputate sapien mauris massa, dolor eget arcu ligula dis. Purus a vel. Potenti quam arcu ut justo, ipsum rhoncus tempor. Mattis etiam. At ipsum non quis viverra leo viverra, mi sodales, eleifend feugiat nascetur sodales quam a eget, nunc nunc lorem fusce quis.\n" +
                        "\n" +
                        "Etiam donec fringilla suspendisse mi, egestas metus fermentum donec conubia dui turpis. In a et in, turpis wisi, urna augue sed class blandit mauris. Sapien fusce fugiat tortor at dolor tempor, justo proin turpis mauris felis diam vestibulum, fusce cras sit elit. Adipiscing augue maiores et id elementum, porta tellus non vel amet donec, sed rutrum vitae euismod volutpat mauris leo. Elit nec amet metus vel. Sit id montes duis, vehicula donec. Nec diam platea pede vel, tristique nullam duis elit laoreet, ipsum donec, ullamcorper iaculis blandit in. Metus varius congue, posuere wisi proin velit, sem et mus nullam morbi, neque nostra. Luctus quis, bibendum nisl risus lorem nunc pede, ipsum vel felis, donec conubia dolor maecenas suspendisse justo commodo. Mauris neque, egestas dui litora mus sit nibh. Augue cras lectus nec, convallis sociis sed duis tempus leo, turpis leo ligula quis vulputate accusantium cum, mauris pellentesque hendrerit a facilisi eu congue, nullam velit. In consequat.\n" +
                        "\n" +
                        "Sem eu in metus in, erat risus mus suscipit placerat non, quis sollicitudin nulla dolor sem tellus justo, blandit class erat egestas, hymenaeos ut nulla mauris at placerat. Dictum dui fusce ipsum velit, eget est morbi, et arcu nam dictum eu justo ligula, id velit risus. Pellentesque scelerisque vitae, quis in quis mauris enim mattis lectus. Ut in quis, dolor sed interdum placerat. Nullam quis, ac pharetra feugiat congue est, velit malesuada quis nibh dolor sociis, condimentum non, nullam neque et suscipit mi class sodales. Rhoncus congue quis ac, ipsum sed, lectus magna et id, consectetuer aliquam diam, vehicula vestibulum donec auctor. In sit, dolor auctor, in ipsum at posuere, tellus in lectus felis dui odio. Accumsan vel magna, magna et tristique, eros etiam nisl nec sodales, sed rutrum magna et venenatis eu, sollicitudin non quisque diam felis ac. Mauris id, suscipit ante suspendisse, mattis id pellentesque non et. Eros hac placerat sed, accumsan bibendum est in lobortis, ante at.\n" +
                        "\n" +
                        "Porttitor mollis vel. Turpis quam mauris mattis iaculis nulla eiusmod, placerat in sapien ut, sed turpis consequatur, rhoncus ipsum felis amet nibh. Curabitur donec lectus odio sit, est pretium lectus id wisi rutrum, suspendisse dolor elit suspendisse. Vel ipsum, quam aliquet, eu metus pharetra rutrum, irure turpis eu ante, ac sagittis nibh posuere. Mollis consequat, vestibulum vel ipsum praesent lobortis turpis. Suspendisse dui justo mollis, pellentesque est lectus ligula aliquet. Consequatur wisi, odio cras in in, ut sed mauris in est leo justo. Wisi vitae eu varius, amet expedita tempor ultrices massa in placerat, risus magna, ac vel est, ut velit nunc nam diam aliquam sit. Quam vel at, sit eget laoreet. Auctor arcu, neque in ac amet metus duis pede. Dictum praesent ante quisque est nonummy. Est sociosqu.\n" +
                        "\n" +
                        "Augue ornare sed amet, amet molestie in integer porta erat, erat ac suscipit. Curabitur elit auctor mauris, eu eu. Nunc sollicitudin imperdiet rhoncus sed maecenas ac, pellentesque suspendisse. Vehicula fermentum accumsan porta eu suspendisse. Vulputate nulla, urna nunc non ac arcu aenean aute.\n" +
                        "\n" +
                        "Donec eros congue sem nec, arcu justo integer pede tortor a wisi, eu lacus a sed. Dolor felis mi pede molestie lorem at, libero erat sit urna, fames fringilla ut do nec tincidunt, maecenas ornare et iaculis mauris nulla, mi eu est magna elit integer. Urna cras neque ipsum, etiam sed, nonummy vitae sed non magna, vel praesent dictum. Sed magna eros tellus in vel, a posuere et wisi, et dui ut purus nullam donec, odio quam libero scelerisque elit suspendisse maecenas. Vel mauris. Hac mi diam leo risus adipiscing convallis, scelerisque volutpat gravida lacinia sed, urna posuere leo occaecati erat, sapiente vel nonummy porta purus, lectus tristique sed est vivamus. Diam rutrum, eros nulla, amet ut tristique ut, aliquam libero dui facilisis nullam netus.\n" +
                        "\n" +
                        "Id eget at consectetuer, suspendisse congue, sit sit et a neque. Et id mollis, tempus at eget cras sed a. Est vestibulum maecenas quam ante, lacus velit tortor vulputate turpis, magna quisque eleifend vel, vel sed odio enim ac ut, sed aenean. Quam sodales amet leo. Libero quam velit lectus dui, adipiscing id porttitor metus libero in consectetuer, erat eget in pharetra risus a nec, hac eleifend turpis nullam ut aute vel.\n" +
                        "\n" +
                        "Nulla posuere erat vestibulum suscipit leo blandit, sit fusce habitasse in integer metus, inceptos luctus id eu sit fusce convallis, quam vitae in amet, mi facilisi. Lectus potenti suspendisse ultrices, ac wisi donec sed eros sit, maecenas vel ipsum turpis elit eu, sit leo, fusce mi eu sapien ultrices vestibulum. Purus ut primis in, ipsum rutrum enim in maecenas nunc. In congue mattis morbi morbi, at blandit praesent potenti nulla purus ut, sed eu et nunc blandit interdum, inceptos hendrerit, faucibus porta viverra. Porttitor dolor, duis rutrum sociis nec, sed sodales nullam diam lorem amet nunc, orci vitae aliquam nisl vestibulum ridiculus nisl.\n" +
                        "\n" +
                        "Sed non pellentesque consectetuer, pellentesque eu primis suspendisse, id fusce et euismod elit vestibulum. Ut interdum neque ut ipsum, tristique dapibus ultrices id, ultricies ultrices mauris. Facilisis sed lacus pellentesque nulla suscipit, ac a imperdiet duis faucibus mi auctor, nec urna turpis et, libero consectetuer gravida accumsan odio ac id, leo elementum dolor facilisi arcu eros commodo. At aenean mauris lobortis libero, aenean sed consectetuer id metus elit molestie, ullamco mollis magna mattis nunc laoreet ut, vitae sociosqu dictum mauris curabitur blandit mauris. Molestie tellus, gravida morbi placerat maecenas aliquam erat est, tempus nostra ac turpis, leo fringilla. Ipsum et interdum est sed, convallis hendrerit venenatis blanditiis nec fusce consequat, cras neque vitae rhoncus orci. Viverra sollicitudin duis diam, dolor erat, vulputate veniam vestibulum non, duis eu ornare, animi erat elit sit condimentum morbi et.\n" +
                        "\n" +
                        "Suscipit venenatis in pretium sed tortor etiam, enim tellus eu, metus erat in nunc condimentum, nec lacus, justo et pellentesque mauris ut. Facilisis dolor tempus. Turpis suscipit in, amet ut fusce, leo ac maecenas sodales, sit vestibulum vestibulum arcu. Nec nulla nec lectus fusce suscipit, dignissim eros massa id praesent magna, ipsum pellentesque maecenas diam odio amet dolor, placerat accumsan ante eu est. Nibh felis ut, porttitor magnis, ante quam mauris arcu volutpat, mauris in augue placerat est ac placerat, wisi eu aenean dui feugiat vestibulum.\n" +
                        "\n" +
                        "Blanditiis at dolor, erat nunc in nulla pretium ante sed. Pede nonummy malesuada ipsum, eget fringilla, nulla pellentesque donec, pulvinar dolor ornare dictumst erat amet massa, conubia libero neque et tempor tortor donec. Aliquet rutrum erat nunc interdum risus, orci diam, ultricies in. Consequat quis ac sem dolor, proin amet quis, eu wisi sollicitudin, accumsan morbi, id nibh pellentesque eu purus id ipsam. Risus amet. Ligula nulla nibh, mauris proin pede nibh purus integer laoreet.\n" +
                        "\n" +
                        "Nullam pede semper augue diam, sit feugiat rhoncus sollicitudin a etiam. Sociosqu eget duis hendrerit nec semper felis, porttitor justo amet, id ea aliquam ante habitasse et, erat leo. Amet phasellus pulvinar, libero massa nunc cubilia adipiscing diam, montes class morbi condimentum curabitur aliquet ut, aliquam nulla nullam sed nec pretium praesent. Vehicula id vel, nostra lorem dolor libero sodales senectus elit. Ultrices a ullamcorper ligula maecenas nec, quisque integer est orci magna, porttitor nunc, et dicta id eget molestie porta aliquam.\n" +
                        "\n" +
                        "Orci non dui risus, id pellentesque duis eu morbi at urna. Fusce mi ut amet ut nonummy, dapibus in vel ultrices aenean aliquam hendrerit. Nulla fermentum integer ut sit luctus, accumsan nec suscipit laboriosam curabitur hymenaeos, pede non eu nec. Eros euismod non ipsum nisl. Accumsan malesuada in, sit malesuada, porttitor id ipsum, erat suscipit. Arcu id, ligula ut nulla donec cras, id augue donec rutrum wisi ipsum tincidunt, ab netus dapibus sollicitudin. Cras nibh a et integer vitae, scelerisque vestibulum lorem placerat fermentum egestas, commodo vel non a nec ac ac. Duis sed fusce odio pharetra sed, libero enim sociosqu tempor, nunc at duis magna, amet donec ac ut nullam, nec in per nonummy ante ante ante.\n" +
                        "\n" +
                        "Suscipit et nonummy, diam ante nec leo eget. Pellentesque magnis, et mi. Consectetuer vestibulum vitae. Nulla lectus nec. Tincidunt id laoreet accumsan id sed magna, per velit mauris tempus. Et sagittis tristique cursus posuere, elit amet convallis parturient lectus molestie, integer quam. Sed nisl ipsum orci turpis, eros hac habitant inceptos, urna nunc arcu ultrices habitasse sollicitudin amet. Ut nam, velit hendrerit suspendisse, tellus qui at, quisque molestie non, nam hendrerit lacinia aliquam. Nulla sed id id urna dui phasellus. Nunc maecenas aliquam neque et est varius. Purus porttitor elementum.\n" +
                        "\n" +
                        "Ligula risus et commodo felis enim, parturient sodales ante dignissimos pellentesque sociosqu in, dictum sapien vestibulum dui. At purus arcu eget tortor mi nulla, nulla donec adipiscing, interdum augue amet et pharetra quam, urna ante orci dui odio lacinia magna. Sed at consectetuer auctor arcu dapibus bibendum. Eget maxime quis diam, sed praesent amet pretium quisque sed, malesuada aliquam, urna mattis suscipit dapibus vehicula ipsum ipsum. Nec aliquet posuere, mauris vitae in morbi in vel. Turpis imperdiet et mauris, augue euismod donec et fusce platea, metus pretium dolor. In dapibus ante eu at et, ligula urna in ipsum dignissim, cursus ut fermentum mollis sollicitudin placerat nullam, scelerisque ligula orci quis tempor nibh vestibulum, porta sed. Tortor in proin quis id ridiculus, in enim iaculis, platea ante sit. Potenti integer ultricies pede nullam ipsum eu, vestibulum est at feugiat, pellentesque nec at luctus sapien, nec nulla in fermentum. Mauris ipsum justo vestibulum felis ut quis, ipsum sapiente in massa aliquam lorem euismod, ultrices faucibus malesuada, sed ut semper sapien urna, aliquam ut nibh sit ea.\n" +
                        "\n" +
                        "Vestibulum neque eget netus malesuada. Dictum mauris lacinia, nullam interdum accusantium elementum. Maecenas venenatis ut, sed vel inceptos nullam nec ut. Libero in vestibulum nulla, vitae arcu risus, viverra felis donec nunc mi duis. Metus vivamus, condimentum luctus vel tortor mauris amet luctus, quam nisl neque lacus massa natoque.\"}";
                producer.send(message.getBytes());
                i++;
            }
            long duration = new Date().getTime() - startTime;
            System.out.println("Duration " + duration);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
}

/*
100,000
INFO: [auto_produce_bytes] [standalone-2-85] Pending messages: 1 --- Publish throughput: 641.62 msg/s --- 0.30 Mbit/s --- Latency: med: 1.537 ms - 95pct: 1.812 ms - 99pct: 2.027 ms - 99.9pct: 2.273 ms - max: 23.356 ms --- Ack received rate: 641.61 ack/s --- Failed messages: 0
Nov 26, 2019 2:05:13 PM org.apache.pulsar.client.impl.ProducerStatsRecorderImpl lambda$init$0
INFO: [auto_produce_bytes] [standalone-2-85] Pending messages: 1 --- Publish throughput: 654.36 msg/s --- 0.31 Mbit/s --- Latency: med: 1.530 ms - 95pct: 1.692 ms - 99pct: 1.797 ms - 99.9pct: 1.954 ms - max: 37.138 ms --- Ack received rate: 654.36 ack/s --- Failed messages: 0
Duration 154345
 */